import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Features',
      link: {
        type: 'generated-index',
        title: 'Features',
        description:
          'Spotlight on every user-facing feature in Folio. Each page is a self-contained tour of one part of the app.',
      },
      items: [
        'features/reader',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: {type: 'doc', id: 'architecture/overview'},
      items: [
        'architecture/multi-select',
        'architecture/library-scanner',
        'architecture/ocr',
        'architecture/spec',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      link: {type: 'doc', id: 'operations/deploy'},
      items: [
        'operations/runtime-configuration',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      link: {type: 'doc', id: 'contributing/setup'},
      items: [
        'contributing/card-corner-conventions',
        'contributing/environment',
      ],
    },
    'references',
  ],
  api: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
