//! SeaORM entity definitions.
//!
//! Phase 0 entities only:
//!   - [`user`]                — local + OIDC users, role, token_version
//!   - [`auth_session`]        — refresh-token rows
//!   - [`library_user_access`] — per-user library ACL (schema in Phase 1, UI Phase 5)
//!   - [`audit_log`]           — append-only admin/security action log
//!
//! Library/series/issue entities arrive in Phase 1a. Until then this crate
//! stays small.

pub mod app_password;
pub mod app_setting;
pub mod audit_log;
pub mod auth_session;
pub mod catalog_source;
pub mod cbl_entry;
pub mod cbl_list;
pub mod cbl_refresh_log;
pub mod character;
pub mod collection_entry;
pub mod concept;
pub mod external_id;
pub mod field_provenance;
pub mod imprint;
pub mod issue;
pub mod issue_arc;
pub mod issue_character;
pub mod issue_concept;
pub mod issue_cover;
pub mod issue_credit;
pub mod issue_genre;
pub mod issue_location;
pub mod issue_object;
pub mod issue_reprint;
pub mod issue_tag;
pub mod issue_team;
pub mod issue_universe;
pub mod library;
pub mod library_event;
pub mod library_health_issue;
pub mod library_user_access;
pub mod location;
pub mod log_widget;
pub mod marker;
pub mod metadata_cache;
pub mod metadata_batch;
pub mod metadata_match_outcome;
pub mod metadata_run;
pub mod metadata_run_candidate;
pub mod object;
pub mod person;
pub mod progress_record;
pub mod publisher;
pub mod rail_dismissal;
pub mod reading_session;
pub mod saved_view;
pub mod scan_batch;
pub mod scan_run;
pub mod series;
pub mod series_arc;
pub mod series_character;
pub mod series_concept;
pub mod series_cover;
pub mod series_credit;
pub mod series_genre;
pub mod series_location;
pub mod series_object;
pub mod series_tag;
pub mod series_team;
pub mod series_universe;
pub mod story_arc;
pub mod team;
pub mod universe;
pub mod user;
pub mod user_page;
pub mod user_rating;
pub mod user_series_progress;
pub mod user_sidebar_entry;
pub mod user_view_pin;

pub mod prelude {
    pub use super::app_password::Entity as AppPassword;
    pub use super::app_setting::Entity as AppSetting;
    pub use super::audit_log::Entity as AuditLog;
    pub use super::auth_session::Entity as AuthSession;
    pub use super::catalog_source::Entity as CatalogSource;
    pub use super::cbl_entry::Entity as CblEntry;
    pub use super::cbl_list::Entity as CblList;
    pub use super::cbl_refresh_log::Entity as CblRefreshLog;
    pub use super::character::Entity as Character;
    pub use super::collection_entry::Entity as CollectionEntry;
    pub use super::concept::Entity as Concept;
    pub use super::external_id::Entity as ExternalId;
    pub use super::field_provenance::Entity as FieldProvenance;
    pub use super::imprint::Entity as Imprint;
    pub use super::issue::Entity as Issue;
    pub use super::issue_arc::Entity as IssueArc;
    pub use super::issue_character::Entity as IssueCharacter;
    pub use super::issue_concept::Entity as IssueConcept;
    pub use super::issue_cover::Entity as IssueCover;
    pub use super::issue_credit::Entity as IssueCredit;
    pub use super::issue_genre::Entity as IssueGenre;
    pub use super::issue_location::Entity as IssueLocation;
    pub use super::issue_object::Entity as IssueObject;
    pub use super::issue_reprint::Entity as IssueReprint;
    pub use super::issue_tag::Entity as IssueTag;
    pub use super::issue_team::Entity as IssueTeam;
    pub use super::issue_universe::Entity as IssueUniverse;
    pub use super::library::Entity as Library;
    pub use super::library_event::Entity as LibraryEvent;
    pub use super::library_health_issue::Entity as LibraryHealthIssue;
    pub use super::library_user_access::Entity as LibraryUserAccess;
    pub use super::location::Entity as Location;
    pub use super::marker::Entity as Marker;
    pub use super::metadata_cache::Entity as MetadataCache;
    pub use super::metadata_match_outcome::Entity as MetadataMatchOutcome;
    pub use super::metadata_run::Entity as MetadataRun;
    pub use super::metadata_run_candidate::Entity as MetadataRunCandidate;
    pub use super::object::Entity as Object;
    pub use super::person::Entity as Person;
    pub use super::progress_record::Entity as ProgressRecord;
    pub use super::publisher::Entity as Publisher;
    pub use super::rail_dismissal::Entity as RailDismissal;
    pub use super::reading_session::Entity as ReadingSession;
    pub use super::saved_view::Entity as SavedView;
    pub use super::scan_batch::Entity as ScanBatch;
    pub use super::scan_run::Entity as ScanRun;
    pub use super::series::Entity as Series;
    pub use super::series_arc::Entity as SeriesArc;
    pub use super::series_character::Entity as SeriesCharacter;
    pub use super::series_concept::Entity as SeriesConcept;
    pub use super::series_cover::Entity as SeriesCover;
    pub use super::series_credit::Entity as SeriesCredit;
    pub use super::series_genre::Entity as SeriesGenre;
    pub use super::series_location::Entity as SeriesLocation;
    pub use super::series_object::Entity as SeriesObject;
    pub use super::series_tag::Entity as SeriesTag;
    pub use super::series_team::Entity as SeriesTeam;
    pub use super::series_universe::Entity as SeriesUniverse;
    pub use super::story_arc::Entity as StoryArc;
    pub use super::team::Entity as Team;
    pub use super::universe::Entity as Universe;
    pub use super::user::Entity as User;
    pub use super::user_page::Entity as UserPage;
    pub use super::user_rating::Entity as UserRating;
    pub use super::user_series_progress::Entity as UserSeriesProgress;
    pub use super::user_sidebar_entry::Entity as UserSidebarEntry;
    pub use super::user_view_pin::Entity as UserViewPin;
}
