//! Post-scan task pipeline (spec §4.8).
//!
//! Three queues are wired here:
//!   - `post_scan_thumbs` — generates one issue's cover thumbnail by default.
//!     Reader page-strip thumbnails are generated by the same queue only after
//!     a strip miss, so scans do not eagerly encode every page in large
//!     libraries. Cover jobs are enqueued by the scanner at scan completion
//!     for issues whose `thumbnails_generated_at IS NULL` or whose stamped
//!     `thumbnail_version < CURRENT`.
//!   - `post_scan_search` — refresh `search_docs` for the library. The
//!     handler today no-ops because the search backend (Phase 2 work) is
//!     keyed by issue.id; the row insert in `process::ingest_one` is enough
//!     for now. The hook is still wired so the future trigram-rebuild step
//!     doesn't need new infrastructure.
//!   - `post_scan_dictionary` — same shape as `post_scan_search`; the
//!     "did you mean" trigram dictionary refresh hooks here when it ships.
//!
//! `relationship_suggestion` and `story_arc_auto_build` slots from the spec
//! are intentionally NOT registered yet — they own tables that don't exist
//! in the current schema.

use crate::library::events::ScanEvent;
use crate::library::thumbnails::{self, THUMBNAIL_VERSION, ThumbFormat, ThumbnailQuality};
use crate::state::AppState;
use apalis::prelude::*;
use entity::{issue, library};
use sea_orm::sea_query::Expr;
use sea_orm::{
    ActiveModelTrait, ColumnTrait, Condition, EntityTrait, QueryFilter, QuerySelect, Set,
};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Generate one thumbnail job for an issue. Cover jobs stamp the issue row
/// with the generation timestamp + version on success. Strip jobs fill the
/// reader page map lazily and only stamp `thumbnails_error` when generation
/// fails.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThumbsJob {
    pub issue_id: String,
    #[serde(default)]
    pub kind: ThumbsJobKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum ThumbsJobKind {
    #[default]
    Cover,
    Strip,
    CoverAndStrip,
}

impl ThumbsJobKind {
    fn as_str(self) -> &'static str {
        match self {
            Self::Cover => "cover",
            Self::Strip => "page_map",
            Self::CoverAndStrip => "cover_page_map",
        }
    }
}

impl ThumbsJob {
    pub fn cover(issue_id: impl Into<String>) -> Self {
        Self {
            issue_id: issue_id.into(),
            kind: ThumbsJobKind::Cover,
        }
    }

    pub fn strip(issue_id: impl Into<String>) -> Self {
        Self {
            issue_id: issue_id.into(),
            kind: ThumbsJobKind::Strip,
        }
    }

    pub fn cover_and_strip(issue_id: impl Into<String>) -> Self {
        Self {
            issue_id: issue_id.into(),
            kind: ThumbsJobKind::CoverAndStrip,
        }
    }

    fn dedupe_key(&self) -> String {
        format!("{}:{:?}", self.issue_id, self.kind)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchJob {
    pub library_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DictionaryJob {
    pub library_id: Uuid,
}

pub async fn handle_thumbs(job: ThumbsJob, state: Data<AppState>) -> Result<(), Error> {
    let app: AppState = (*state).clone();
    let dedupe_key = job.dedupe_key();

    // Look up the issue. A missing row means the issue was deleted between
    // enqueue and execution — drop silently.
    let row = match issue::Entity::find_by_id(job.issue_id.clone())
        .one(&app.db)
        .await
    {
        Ok(Some(r)) => r,
        Ok(None) => {
            tracing::debug!(issue_id = %job.issue_id, "thumbs job: issue gone");
            app.unmark_thumb_job_queued(&dedupe_key).await;
            return Ok(());
        }
        Err(e) => {
            tracing::error!(issue_id = %job.issue_id, error = %e, "thumbs job: db lookup failed");
            return Err(Error::Failed(std::sync::Arc::new(Box::new(e))));
        }
    };

    if row.state != "active" {
        tracing::debug!(
            issue_id = %job.issue_id,
            state = %row.state,
            "thumbs job: skipping non-active issue",
        );
        app.unmark_thumb_job_queued(&dedupe_key).await;
        return Ok(());
    }

    // Look up the library so we honor `thumbnails_enabled` and use the
    // configured format. A job that landed before the admin disabled the
    // toggle drops silently — existing thumbs keep serving and the admin's
    // intent (no new generation) is respected.
    let lib = match library::Entity::find_by_id(row.library_id)
        .one(&app.db)
        .await
    {
        Ok(Some(l)) => l,
        Ok(None) => {
            tracing::debug!(library_id = %row.library_id, "thumbs job: library gone");
            app.unmark_thumb_job_queued(&dedupe_key).await;
            return Ok(());
        }
        Err(e) => {
            tracing::error!(library_id = %row.library_id, error = %e, "thumbs job: library lookup failed");
            return Err(Error::Failed(std::sync::Arc::new(Box::new(e))));
        }
    };
    if !lib.thumbnails_enabled {
        tracing::debug!(library_id = %lib.id, "thumbs job: library has thumbnails disabled, skipping");
        app.unmark_thumb_job_queued(&dedupe_key).await;
        return Ok(());
    }
    let format = ThumbFormat::parse(&lib.thumbnail_format).unwrap_or_default();
    let quality = ThumbnailQuality::new(lib.thumbnail_cover_quality, lib.thumbnail_page_quality);

    app.events.emit(ScanEvent::ThumbsStarted {
        library_id: row.library_id,
        issue_id: row.id.clone(),
        kind: job.kind.as_str().to_owned(),
    });

    let data_dir = app.cfg().data_path.clone();
    let issue_id = row.id.clone();
    let file_path = row.file_path.clone();
    let kind = job.kind;
    // M6: capture the per-issue cover page from the row. Pre-M6 the
    // post-scan worker always read page 0; now it reads whatever the
    // scanner stamped from ComicInfo's `<Page Type="FrontCover"/>`
    // marker. Clamped to `usize::MAX` for safety against a negative
    // value (the column is NOT NULL but defensive).
    let cover_page_index: usize = row.cover_page_index.max(0) as usize;
    // `ArchiveLimits` is `Copy`; capture before spawn_blocking so the
    // post-scan archive open honors any `COMIC_ARCHIVE_MAX_*` overrides.
    let archive_limits = app.cfg().archive_limits();

    let outcome = match app.archive_work_semaphore.clone().acquire_owned().await {
        Ok(permit) => {
            tokio::task::spawn_blocking(move || {
                let _permit = permit;
                let mut archive = archive::open(std::path::Path::new(&file_path), archive_limits)?;
                // For cover jobs: decode the cover page once and use
                // the same `DynamicImage` for both perceptual hashing
                // (matcher.rs constants are calibrated against
                // archive-source hashes, not re-encoded WebP
                // thumbnails — see metadata::phash::compute_archive_cover
                // docs) and thumbnail encoding. Decoding once spares
                // a second zip-read + decode per issue.
                let mut cover_hashes: Option<crate::metadata::phash::ArchiveCoverHashes> = None;
                let cover_result: Result<(), thumbnails::ThumbError> = if matches!(
                    kind,
                    ThumbsJobKind::Cover | ThumbsJobKind::CoverAndStrip
                ) {
                    match thumbnails::decode_page(&mut *archive, cover_page_index) {
                        Ok(img) => {
                            let (p, d, a) = crate::metadata::phash::all_hashes(&img);
                            cover_hashes = Some(crate::metadata::phash::ArchiveCoverHashes {
                                hashes: (p, d, a),
                                width: img.width() as i32,
                                height: img.height() as i32,
                            });
                            thumbnails::encode_cover_from_image(
                                &data_dir,
                                &issue_id,
                                cover_page_index,
                                &img,
                                format,
                                quality,
                            )
                            .map(|_| ())
                        }
                        Err(e) => Err(e),
                    }
                } else {
                    Ok(())
                };
                let outcome: Result<thumbnails::GenerateAllOutcome, thumbnails::ThumbError> =
                    match kind {
                        ThumbsJobKind::Cover => cover_result.map(|_| {
                            thumbnails::GenerateAllOutcome {
                                total_pages: 1,
                                failed: Vec::new(),
                            }
                        }),
                        ThumbsJobKind::Strip => thumbnails::generate_strips_with_quality(
                            &data_dir,
                            &mut *archive,
                            &issue_id,
                            format,
                            quality,
                        ),
                        ThumbsJobKind::CoverAndStrip => cover_result.and_then(|_| {
                            let mut strips = thumbnails::generate_strips_with_quality(
                                &data_dir,
                                &mut *archive,
                                &issue_id,
                                format,
                                quality,
                            )?;
                            strips.total_pages = strips.total_pages.saturating_add(1);
                            Ok(strips)
                        }),
                    };
                outcome.map(|o| (o, cover_hashes))
            })
            .await
        }
        Err(e) => {
            tracing::warn!(issue_id = %row.id, error = %e, "thumbs job: archive semaphore closed");
            stamp_error(&app, &row, "archive work unavailable".to_owned()).await;
            app.unmark_thumb_job_queued(&dedupe_key).await;
            return Ok(());
        }
    };

    match outcome {
        Ok(Ok((o, cover_hashes))) => {
            if !o.failed.is_empty() {
                let preview = o
                    .failed
                    .iter()
                    .take(3)
                    .map(|(n, e)| format!("p{n}: {e}"))
                    .collect::<Vec<_>>()
                    .join(", ");
                tracing::warn!(
                    issue_id = %row.id,
                    pages_failed = o.failed.len(),
                    preview = %preview,
                    "thumbs job: some pages failed to encode",
                );
            }
            if matches!(
                job.kind,
                ThumbsJobKind::Cover | ThumbsJobKind::CoverAndStrip
            ) {
                stamp_done(&app, &row).await;
                // Persist the perceptual hashes computed against the
                // *source* archive page (not the WebP thumbnail) so
                // the matcher's ComicTagger-derived Hamming ladder
                // sees the same kind of bytes ComicVine / Metron host.
                // Failure here is non-fatal — the cover still displays,
                // the matching engine just falls back to text-only for
                // this issue until the backfill job catches it.
                if let Some(h) = cover_hashes
                    && let Err(e) = persist_cover_phash_from_parts(&app, &row, h).await
                {
                    tracing::debug!(
                        issue_id = %row.id,
                        error = %e,
                        "thumbs job: cover phash persist failed (non-fatal)"
                    );
                }
            }
            if matches!(
                job.kind,
                ThumbsJobKind::Strip | ThumbsJobKind::CoverAndStrip
            ) {
                if !o.failed.is_empty() {
                    let msg = format!("{} strip pages failed", o.failed.len());
                    stamp_error(&app, &row, msg).await;
                }
                // Self-heal: when the archive's actual page count disagrees
                // with the ComicInfo-derived `page_count` we stamped at scan
                // time, reconcile to the archive truth. The strip generator
                // only encodes pages that exist on disk, so leaving a stale
                // count would keep the readiness denominator chasing pages
                // that physically aren't there. Older libraries scanned
                // before scanner-side reconciliation landed pick up the fix
                // the next time their strips are (re)generated.
                reconcile_page_count(&app, &row, o.total_pages).await;
            }
            app.events.emit(ScanEvent::ThumbsCompleted {
                library_id: row.library_id,
                issue_id: row.id.clone(),
                kind: job.kind.as_str().to_owned(),
                pages: o.total_pages as u64,
            });
            app.unmark_thumb_job_queued(&dedupe_key).await;
            Ok(())
        }
        Ok(Err(e)) => {
            let msg = e.to_string();
            tracing::warn!(issue_id = %row.id, error = %e, "thumbs job: cover generation failed");
            stamp_error(&app, &row, msg.clone()).await;
            app.events.emit(ScanEvent::ThumbsFailed {
                library_id: row.library_id,
                issue_id: row.id.clone(),
                kind: job.kind.as_str().to_owned(),
                error: msg,
            });
            app.unmark_thumb_job_queued(&dedupe_key).await;
            Ok(())
        }
        Err(e) => {
            let msg = format!("worker panic: {e}");
            tracing::error!(issue_id = %row.id, error = %e, "thumbs job: blocking task panicked");
            stamp_error(&app, &row, msg.clone()).await;
            app.events.emit(ScanEvent::ThumbsFailed {
                library_id: row.library_id,
                issue_id: row.id.clone(),
                kind: job.kind.as_str().to_owned(),
                error: msg,
            });
            app.unmark_thumb_job_queued(&dedupe_key).await;
            Err(Error::Failed(std::sync::Arc::new(Box::new(e))))
        }
    }
}

pub async fn enqueue_thumb_job(app: &AppState, job: ThumbsJob) -> bool {
    let key = job.dedupe_key();
    if !app.try_mark_thumb_job_queued(key.clone()).await {
        tracing::debug!(issue_id = %job.issue_id, kind = ?job.kind, "thumbs enqueue: duplicate suppressed");
        return false;
    }

    let mut storage = app.jobs.post_scan_thumbs_storage.clone();
    if let Err(e) = storage.push(job.clone()).await {
        app.unmark_thumb_job_queued(&key).await;
        tracing::warn!(
            issue_id = %job.issue_id,
            kind = ?job.kind,
            error = %e,
            "thumbs enqueue: push failed",
        );
        return false;
    }
    true
}

async fn stamp_done(app: &AppState, row: &issue::Model) {
    let now = chrono::Utc::now().fixed_offset();
    let mut am: issue::ActiveModel = row.clone().into();
    am.thumbnails_generated_at = Set(Some(now));
    am.thumbnail_version = Set(THUMBNAIL_VERSION);
    am.thumbnails_error = Set(None);
    am.updated_at = Set(now);
    if let Err(e) = am.update(&app.db).await {
        tracing::warn!(issue_id = %row.id, error = %e, "thumbs job: stamp_done update failed");
    }
}

/// Update `issue.page_count` to the archive's actual page count when the
/// strip generator's view of reality differs from the row's stamped value.
/// No-op when the counts already agree or when the archive yielded zero
/// pages (which only happens on malformed/encrypted archives the strip
/// handler would never reach a successful outcome for anyway).
async fn reconcile_page_count(app: &AppState, row: &issue::Model, archive_pages: usize) {
    if archive_pages == 0 {
        return;
    }
    let next = archive_pages as i32;
    if row.page_count == Some(next) {
        return;
    }
    let now = chrono::Utc::now().fixed_offset();
    let mut am: issue::ActiveModel = row.clone().into();
    am.page_count = Set(Some(next));
    am.updated_at = Set(now);
    match am.update(&app.db).await {
        Ok(_) => {
            tracing::info!(
                issue_id = %row.id,
                previous = ?row.page_count,
                actual = next,
                "thumbs job: reconciled page_count to archive truth",
            );
        }
        Err(e) => {
            tracing::warn!(
                issue_id = %row.id,
                error = %e,
                "thumbs job: page_count reconcile update failed",
            );
        }
    }
}

async fn stamp_error(app: &AppState, row: &issue::Model, msg: String) {
    let now = chrono::Utc::now().fixed_offset();
    let mut am: issue::ActiveModel = row.clone().into();
    am.thumbnails_error = Set(Some(msg));
    // Stamp `thumbnails_generated_at` AND bump `thumbnail_version` to the
    // current sentinel on the error path. Both clauses of the post-scan
    // enqueue query (`generated_at IS NULL` and `version < CURRENT`)
    // must miss this row, otherwise a permanently-failing decode
    // (e.g. a publisher's 928-byte placeholder at position 0) keeps
    // re-cycling through the queue forever and blocks the scan from
    // reporting complete. Operators retry explicitly via "Force
    // recreate" on the admin thumbnails tab, which clears
    // `thumbnails_error` + `thumbnails_generated_at` and re-issues
    // the cover job. A future `THUMBNAIL_VERSION` bump then naturally
    // sweeps everyone (success or failure) into a fresh attempt.
    am.thumbnails_generated_at = Set(Some(now));
    am.thumbnail_version = Set(crate::library::thumbnails::THUMBNAIL_VERSION);
    am.updated_at = Set(now);
    if let Err(e) = am.update(&app.db).await {
        tracing::warn!(issue_id = %row.id, error = %e, "thumbs job: stamp_error update failed");
    }
}

/// `WHERE` clause for "this issue needs the post-scan cover worker
/// to run." Three disjoint triggers:
///   1. Thumbnail never generated (`thumbnails_generated_at IS NULL`)
///   2. Thumbnail stale (`thumbnail_version < CURRENT`)
///   3. Thumbnail current, but the archive-extracted phash row is
///      missing or NULL — the matcher's cover discriminant can't
///      fire without it, so a scan should top up the hash even when
///      the visible thumb is fine. `handle_thumbs` then decodes the
///      archive cover page once, hashes it, and the no-op encoder
///      short-circuits because the existing thumb is still current.
fn needs_cover_work_filter() -> Condition {
    Condition::any()
        .add(issue::Column::ThumbnailsGeneratedAt.is_null())
        .add(issue::Column::ThumbnailVersion.lt(THUMBNAIL_VERSION))
        .add(Expr::cust(
            r#"NOT EXISTS (
                SELECT 1 FROM issue_cover ic
                WHERE ic.issue_id = issues.id
                  AND ic.kind = 'primary'
                  AND ic.ordinal = 0
                  AND ic.source_provider = 'archive_extracted'
                  AND ic.phash IS NOT NULL
            )"#,
        ))
}

/// Bulk-enqueue a cover job for every issue in `library_id` whose cover
/// thumbnail is missing (`thumbnails_generated_at IS NULL`) or stale
/// (`thumbnail_version < THUMBNAIL_VERSION`) or whose archive-extracted
/// perceptual hash hasn't been computed yet. Returns the number of jobs
/// pushed after process-local dedupe. Best-effort — if the apalis push fails
/// for any issue, the error is logged and the loop continues.
///
/// Honors the per-library `thumbnails_enabled` toggle: when disabled, the
/// function returns `0` without enqueueing anything. Existing on-disk
/// thumbnails keep serving; the admin can flip the toggle back on or run
/// "Generate missing" later.
pub async fn enqueue_pending_for_library(app: &AppState, library_id: Uuid) -> usize {
    match library::Entity::find_by_id(library_id).one(&app.db).await {
        Ok(Some(lib)) if !lib.thumbnails_enabled => {
            tracing::debug!(
                library_id = %library_id,
                "thumbs enqueue: library has thumbnails disabled, skipping",
            );
            return 0;
        }
        Ok(Some(_)) => {}
        Ok(None) => {
            tracing::debug!(library_id = %library_id, "thumbs enqueue: library gone");
            return 0;
        }
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "thumbs enqueue: library lookup failed");
            return 0;
        }
    }

    let pending: Vec<String> = match issue::Entity::find()
        .filter(issue::Column::LibraryId.eq(library_id))
        .filter(issue::Column::State.eq("active"))
        .filter(needs_cover_work_filter())
        .select_only()
        .column(issue::Column::Id)
        .into_tuple::<String>()
        .all(&app.db)
        .await
    {
        Ok(v) => v,
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "thumbs enqueue: query failed");
            return 0;
        }
    };

    let mut count = 0usize;
    for issue_id in pending {
        if enqueue_thumb_job(app, ThumbsJob::cover(issue_id)).await {
            count += 1;
        }
    }
    if count > 0 {
        tracing::info!(library_id = %library_id, count, "thumbs enqueue: pushed jobs");
    }
    count
}

/// Enqueue pending cover jobs for active issues in one series only.
pub async fn enqueue_pending_for_series(
    app: &AppState,
    library_id: Uuid,
    series_id: Uuid,
) -> usize {
    let ids: Vec<String> = match issue::Entity::find()
        .filter(issue::Column::LibraryId.eq(library_id))
        .filter(issue::Column::SeriesId.eq(series_id))
        .filter(issue::Column::State.eq("active"))
        .filter(needs_cover_work_filter())
        .select_only()
        .column(issue::Column::Id)
        .into_tuple::<String>()
        .all(&app.db)
        .await
    {
        Ok(v) => v,
        Err(e) => {
            tracing::error!(library_id = %library_id, series_id = %series_id, error = %e, "thumbs enqueue: series query failed");
            return 0;
        }
    };
    enqueue_pending_for_issue_ids(app, library_id, ids).await
}

/// Post-scan eager thumbnail fanout. Scans only enqueue missing/stale cover
/// work; page-map strips remain lazy or explicit admin work so a routine scan
/// does not flood the queue with every page in the library.
pub async fn enqueue_post_scan_for_library(app: &AppState, library_id: Uuid) -> usize {
    let (rows, include_strips) = match active_issue_rows_for_thumbs(app, library_id, None).await {
        Some(pair) => pair,
        None => return 0,
    };
    enqueue_post_scan_rows(app, rows, include_strips).await
}

pub async fn enqueue_post_scan_for_series(
    app: &AppState,
    library_id: Uuid,
    series_id: Uuid,
) -> usize {
    let (rows, include_strips) =
        match active_issue_rows_for_thumbs(app, library_id, Some(series_id)).await {
            Some(pair) => pair,
            None => return 0,
        };
    enqueue_post_scan_rows(app, rows, include_strips).await
}

/// Returns the issue rows that need post-scan thumbnail work plus a flag
/// for whether the library has opted into auto page-strip generation
/// (`library.generate_page_thumbs_on_scan`). `Some((vec![], _))` means
/// "no work" — distinct from `None` which means "lookup failed, retry
/// later". The flag flows through so the row-level loop can decide
/// per-issue whether to enqueue Strip alongside Cover.
async fn active_issue_rows_for_thumbs(
    app: &AppState,
    library_id: Uuid,
    series_id: Option<Uuid>,
) -> Option<(Vec<issue::Model>, bool)> {
    let include_strips = match library::Entity::find_by_id(library_id).one(&app.db).await {
        Ok(Some(lib)) if !lib.thumbnails_enabled => {
            tracing::debug!(
                library_id = %library_id,
                "post-scan thumbs enqueue: library has thumbnails disabled, skipping",
            );
            return Some((Vec::new(), false));
        }
        Ok(Some(lib)) => lib.generate_page_thumbs_on_scan,
        Ok(None) => return Some((Vec::new(), false)),
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "post-scan thumbs enqueue: library lookup failed");
            return None;
        }
    };

    // Never attempted OR version bumped OR phash missing. Thumb-decode
    // failures are NOT auto-retried — `stamp_error` stamps
    // `generated_at`, so a permanently-failing decode (e.g. corrupt
    // cover image) doesn't loop the post-scan queue forever. Manual
    // retry: admin "Force recreate" clears both columns. Global retry:
    // bump THUMBNAIL_VERSION. The phash-missing branch is independent
    // — it stays satisfied once the hash lands.
    let mut query = issue::Entity::find()
        .filter(issue::Column::LibraryId.eq(library_id))
        .filter(issue::Column::State.eq("active"))
        .filter(needs_cover_work_filter());
    if let Some(series_id) = series_id {
        query = query.filter(issue::Column::SeriesId.eq(series_id));
    }
    match query.all(&app.db).await {
        Ok(rows) => Some((rows, include_strips)),
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "post-scan thumbs enqueue: issue query failed");
            None
        }
    }
}

async fn enqueue_post_scan_rows(
    app: &AppState,
    rows: Vec<issue::Model>,
    include_strips: bool,
) -> usize {
    let mut count = 0usize;
    for row in rows {
        // Trust the upstream query (`active_issue_rows_for_thumbs`)
        // for the cover-or-hash gate — it knows about the phash
        // condition that's not visible from the issue row alone.
        // When the library has `generate_page_thumbs_on_scan = true`,
        // fan out to a CoverAndStrip job so the worker generates both
        // in a single archive open. When false, keep the historical
        // cover-only behavior; admins still have the manual "Generate
        // missing pages" button to fill page thumbs in later. Hash-only
        // catchup runs (thumb already current) still pay this strip
        // cost when the library opted in — the strip encoder no-ops
        // when its target file exists, so it's a few extra disk stats
        // per page.
        let job = if include_strips {
            ThumbsJob::cover_and_strip(row.id)
        } else {
            ThumbsJob::cover(row.id)
        };
        if enqueue_thumb_job(app, job).await {
            count += 1;
        }
    }
    count
}

/// Enqueue pending cover jobs for a known set of issue ids. The DB query
/// re-checks active state and thumbnail freshness so callers can pass ids
/// gathered before ingestion updated content hashes or states.
pub async fn enqueue_pending_for_issue_ids<I>(
    app: &AppState,
    library_id: Uuid,
    issue_ids: I,
) -> usize
where
    I: IntoIterator<Item = String>,
{
    match library::Entity::find_by_id(library_id).one(&app.db).await {
        Ok(Some(lib)) if !lib.thumbnails_enabled => {
            tracing::debug!(
                library_id = %library_id,
                "thumbs enqueue: library has thumbnails disabled, skipping scoped enqueue",
            );
            return 0;
        }
        Ok(Some(_)) => {}
        Ok(None) => {
            tracing::debug!(library_id = %library_id, "thumbs enqueue: library gone");
            return 0;
        }
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "thumbs enqueue: library lookup failed");
            return 0;
        }
    }

    let ids = issue_ids.into_iter().collect::<Vec<_>>();
    if ids.is_empty() {
        return 0;
    }
    let pending: Vec<String> = match issue::Entity::find()
        .filter(issue::Column::LibraryId.eq(library_id))
        .filter(issue::Column::Id.is_in(ids))
        .filter(issue::Column::State.eq("active"))
        .filter(needs_cover_work_filter())
        .select_only()
        .column(issue::Column::Id)
        .into_tuple::<String>()
        .all(&app.db)
        .await
    {
        Ok(v) => v,
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "thumbs enqueue: scoped query failed");
            return 0;
        }
    };

    let mut count = 0usize;
    for issue_id in pending {
        if enqueue_thumb_job(app, ThumbsJob::cover(issue_id)).await {
            count += 1;
        }
    }
    count
}

/// Enqueue one lazy page-map strip job for every active issue in a single
/// series. Mirror of `enqueue_strips_for_library` scoped to one series so
/// admins can rebuild a single book's reader page-map without touching the
/// rest of the library. Strip jobs are file-level idempotent — existing
/// page thumbnails are skipped and only missing pages are encoded.
pub async fn enqueue_strips_for_series(app: &AppState, library_id: Uuid, series_id: Uuid) -> usize {
    match library::Entity::find_by_id(library_id).one(&app.db).await {
        Ok(Some(lib)) if !lib.thumbnails_enabled => {
            tracing::debug!(
                library_id = %library_id,
                series_id = %series_id,
                "strip thumbs enqueue (series): library has thumbnails disabled, skipping",
            );
            return 0;
        }
        Ok(Some(_)) => {}
        Ok(None) => {
            tracing::debug!(library_id = %library_id, "strip thumbs enqueue (series): library gone");
            return 0;
        }
        Err(e) => {
            tracing::error!(library_id = %library_id, series_id = %series_id, error = %e, "strip thumbs enqueue (series): library lookup failed");
            return 0;
        }
    }

    let issue_ids: Vec<String> = match issue::Entity::find()
        .filter(issue::Column::LibraryId.eq(library_id))
        .filter(issue::Column::SeriesId.eq(series_id))
        .filter(issue::Column::State.eq("active"))
        .select_only()
        .column(issue::Column::Id)
        .into_tuple::<String>()
        .all(&app.db)
        .await
    {
        Ok(v) => v,
        Err(e) => {
            tracing::error!(library_id = %library_id, series_id = %series_id, error = %e, "strip thumbs enqueue (series): query failed");
            return 0;
        }
    };

    let mut count = 0usize;
    for issue_id in issue_ids {
        if enqueue_thumb_job(app, ThumbsJob::strip(issue_id)).await {
            count += 1;
        }
    }
    if count > 0 {
        tracing::info!(library_id = %library_id, series_id = %series_id, count, "strip thumbs enqueue (series): pushed jobs");
    }
    count
}

/// Enqueue one lazy page-map strip job for every active issue in a library.
/// Strip jobs are idempotent at the file level: existing page thumbnails are
/// skipped and only missing pages are decoded/encoded.
pub async fn enqueue_strips_for_library(app: &AppState, library_id: Uuid) -> usize {
    match library::Entity::find_by_id(library_id).one(&app.db).await {
        Ok(Some(lib)) if !lib.thumbnails_enabled => {
            tracing::debug!(
                library_id = %library_id,
                "strip thumbs enqueue: library has thumbnails disabled, skipping",
            );
            return 0;
        }
        Ok(Some(_)) => {}
        Ok(None) => {
            tracing::debug!(library_id = %library_id, "strip thumbs enqueue: library gone");
            return 0;
        }
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "strip thumbs enqueue: library lookup failed");
            return 0;
        }
    }

    let issue_ids: Vec<String> = match issue::Entity::find()
        .filter(issue::Column::LibraryId.eq(library_id))
        .filter(issue::Column::State.eq("active"))
        .select_only()
        .column(issue::Column::Id)
        .into_tuple::<String>()
        .all(&app.db)
        .await
    {
        Ok(v) => v,
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "strip thumbs enqueue: query failed");
            return 0;
        }
    };

    let mut count = 0usize;
    for issue_id in issue_ids {
        if enqueue_thumb_job(app, ThumbsJob::strip(issue_id)).await {
            count += 1;
        }
    }
    if count > 0 {
        tracing::info!(library_id = %library_id, count, "strip thumbs enqueue: pushed jobs");
    }
    count
}


pub async fn handle_search(job: SearchJob, _state: Data<AppState>) -> Result<(), Error> {
    tracing::debug!(
        library_id = %job.library_id,
        "post_scan_search (no-op — search_docs is upserted inline today)",
    );
    Ok(())
}

pub async fn handle_dictionary(job: DictionaryJob, _state: Data<AppState>) -> Result<(), Error> {
    // No-op by design. The "did you mean" trigram surface was deferred
    // by decision in incompleteness-cleanup M2 (D-3) — Postgres-side
    // `pg_trgm` similarity hits already cover the common typos without
    // a separate dictionary. The job slot is kept so the cron schedule
    // doesn't need to be rewritten if the decision is ever revisited.
    tracing::trace!(library_id = %job.library_id, "post_scan_dictionary (no-op)");
    Ok(())
}

/// Compute perceptual hashes on the issue's cover thumbnail + upsert
/// an `issue_cover (source_provider='archive_extracted')` row.
/// Idempotent on rescan; fails soft (returns Err but the caller
/// logs at debug level rather than retrying).
///
/// metadata-providers-1.0 M9.
/// Persist a hash triple computed elsewhere (the thumb worker's
/// shared decode of the cover archive page) into the issue's
/// `issue_cover` row. `local_path` is set to the on-disk thumbnail
/// path so the cover-serving fallback still has somewhere to point
/// even though the hashes themselves come from the archive bytes.
async fn persist_cover_phash_from_parts(
    app: &AppState,
    row: &issue::Model,
    parts: crate::metadata::phash::ArchiveCoverHashes,
) -> anyhow::Result<()> {
    let data_dir = app.cfg().data_path.clone();
    let local_path = match thumbnails::find_existing_cover(&data_dir, &row.id) {
        Some(p) => p
            .strip_prefix(&data_dir)
            .map(|p| p.to_string_lossy().into_owned())
            .unwrap_or_else(|_| p.to_string_lossy().into_owned()),
        // Hash row is the matcher's side-channel — write it even when
        // the thumbnail hasn't landed on disk yet. The display path
        // falls back to a fresh inline-generated thumb either way.
        None => String::new(),
    };
    crate::metadata::phash::upsert_archive_cover_hashes_from_parts(
        &app.db,
        &row.id,
        &local_path,
        parts.hashes,
        parts.width,
        parts.height,
    )
    .await?;
    Ok(())
}
