//! Post-scan task pipeline (spec §4.8).
//!
//! Three queues are wired here:
//!   - `post_scan_thumbs` — generates one issue's cover thumbnail by default.
//!     Reader page-strip thumbnails are generated by the same queue only after
//!     a strip miss, so scans do not eagerly encode every page in large
//!     libraries. Cover jobs are enqueued by the scanner at scan completion
//!     for issues whose `thumbnails_generated_at IS NULL` or whose stamped
//!     `thumbnail_version < CURRENT`.
//!   - `post_scan_search` — refresh `search_docs` for the library. The
//!     handler today no-ops because the search backend (Phase 2 work) is
//!     keyed by issue.id; the row insert in `process::ingest_one` is enough
//!     for now. The hook is still wired so the future trigram-rebuild step
//!     doesn't need new infrastructure.
//!   - `post_scan_dictionary` — same shape as `post_scan_search`; the
//!     "did you mean" trigram dictionary refresh hooks here when it ships.
//!
//! `relationship_suggestion` and `story_arc_auto_build` slots from the spec
//! are intentionally NOT registered yet — they own tables that don't exist
//! in the current schema.

use crate::library::events::ScanEvent;
use crate::library::thumbnails::{self, THUMBNAIL_VERSION, ThumbFormat, ThumbnailQuality};
use crate::state::AppState;
use apalis::prelude::*;
use archive::ArchiveLimits;
use entity::{issue, library};
use sea_orm::{
    ActiveModelTrait, ColumnTrait, Condition, EntityTrait, QueryFilter, QuerySelect, Set,
};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Generate one thumbnail job for an issue. Cover jobs stamp the issue row
/// with the generation timestamp + version on success. Strip jobs fill the
/// reader page map lazily and only stamp `thumbnails_error` when generation
/// fails.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThumbsJob {
    pub issue_id: String,
    #[serde(default)]
    pub kind: ThumbsJobKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum ThumbsJobKind {
    #[default]
    Cover,
    Strip,
    CoverAndStrip,
}

impl ThumbsJobKind {
    fn as_str(self) -> &'static str {
        match self {
            Self::Cover => "cover",
            Self::Strip => "page_map",
            Self::CoverAndStrip => "cover_page_map",
        }
    }
}

impl ThumbsJob {
    pub fn cover(issue_id: impl Into<String>) -> Self {
        Self {
            issue_id: issue_id.into(),
            kind: ThumbsJobKind::Cover,
        }
    }

    pub fn strip(issue_id: impl Into<String>) -> Self {
        Self {
            issue_id: issue_id.into(),
            kind: ThumbsJobKind::Strip,
        }
    }

    pub fn cover_and_strip(issue_id: impl Into<String>) -> Self {
        Self {
            issue_id: issue_id.into(),
            kind: ThumbsJobKind::CoverAndStrip,
        }
    }

    fn dedupe_key(&self) -> String {
        format!("{}:{:?}", self.issue_id, self.kind)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchJob {
    pub library_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DictionaryJob {
    pub library_id: Uuid,
}

pub async fn handle_thumbs(job: ThumbsJob, state: Data<AppState>) -> Result<(), Error> {
    let app: AppState = (*state).clone();
    let dedupe_key = job.dedupe_key();

    // Look up the issue. A missing row means the issue was deleted between
    // enqueue and execution — drop silently.
    let row = match issue::Entity::find_by_id(job.issue_id.clone())
        .one(&app.db)
        .await
    {
        Ok(Some(r)) => r,
        Ok(None) => {
            tracing::debug!(issue_id = %job.issue_id, "thumbs job: issue gone");
            app.unmark_thumb_job_queued(&dedupe_key).await;
            return Ok(());
        }
        Err(e) => {
            tracing::error!(issue_id = %job.issue_id, error = %e, "thumbs job: db lookup failed");
            return Err(Error::Failed(std::sync::Arc::new(Box::new(e))));
        }
    };

    if row.state != "active" {
        tracing::debug!(
            issue_id = %job.issue_id,
            state = %row.state,
            "thumbs job: skipping non-active issue",
        );
        app.unmark_thumb_job_queued(&dedupe_key).await;
        return Ok(());
    }

    // Look up the library so we honor `thumbnails_enabled` and use the
    // configured format. A job that landed before the admin disabled the
    // toggle drops silently — existing thumbs keep serving and the admin's
    // intent (no new generation) is respected.
    let lib = match library::Entity::find_by_id(row.library_id)
        .one(&app.db)
        .await
    {
        Ok(Some(l)) => l,
        Ok(None) => {
            tracing::debug!(library_id = %row.library_id, "thumbs job: library gone");
            app.unmark_thumb_job_queued(&dedupe_key).await;
            return Ok(());
        }
        Err(e) => {
            tracing::error!(library_id = %row.library_id, error = %e, "thumbs job: library lookup failed");
            return Err(Error::Failed(std::sync::Arc::new(Box::new(e))));
        }
    };
    if !lib.thumbnails_enabled {
        tracing::debug!(library_id = %lib.id, "thumbs job: library has thumbnails disabled, skipping");
        app.unmark_thumb_job_queued(&dedupe_key).await;
        return Ok(());
    }
    let format = ThumbFormat::parse(&lib.thumbnail_format).unwrap_or_default();
    let quality = ThumbnailQuality::new(lib.thumbnail_cover_quality, lib.thumbnail_page_quality);

    app.events.emit(ScanEvent::ThumbsStarted {
        library_id: row.library_id,
        issue_id: row.id.clone(),
        kind: job.kind.as_str().to_owned(),
    });

    let data_dir = app.cfg.data_path.clone();
    let issue_id = row.id.clone();
    let file_path = row.file_path.clone();
    let kind = job.kind;

    let outcome = match app.archive_work_semaphore.clone().acquire_owned().await {
        Ok(permit) => {
            tokio::task::spawn_blocking(move || {
                let _permit = permit;
                let mut archive =
                    archive::open(std::path::Path::new(&file_path), ArchiveLimits::default())?;
                match kind {
                    ThumbsJobKind::Cover => {
                        thumbnails::generate_with_quality(
                            &data_dir,
                            &mut *archive,
                            &issue_id,
                            thumbnails::Variant::Cover,
                            0,
                            format,
                            quality,
                        )?;
                        Ok(thumbnails::GenerateAllOutcome {
                            total_pages: 1,
                            failed: Vec::new(),
                        })
                    }
                    ThumbsJobKind::Strip => thumbnails::generate_strips_with_quality(
                        &data_dir,
                        &mut *archive,
                        &issue_id,
                        format,
                        quality,
                    ),
                    ThumbsJobKind::CoverAndStrip => {
                        thumbnails::generate_with_quality(
                            &data_dir,
                            &mut *archive,
                            &issue_id,
                            thumbnails::Variant::Cover,
                            0,
                            format,
                            quality,
                        )?;
                        let mut strips = thumbnails::generate_strips_with_quality(
                            &data_dir,
                            &mut *archive,
                            &issue_id,
                            format,
                            quality,
                        )?;
                        strips.total_pages = strips.total_pages.saturating_add(1);
                        Ok(strips)
                    }
                }
            })
            .await
        }
        Err(e) => {
            tracing::warn!(issue_id = %row.id, error = %e, "thumbs job: archive semaphore closed");
            stamp_error(&app, &row, "archive work unavailable".to_owned()).await;
            app.unmark_thumb_job_queued(&dedupe_key).await;
            return Ok(());
        }
    };

    match outcome {
        Ok(Ok(o)) => {
            if !o.failed.is_empty() {
                let preview = o
                    .failed
                    .iter()
                    .take(3)
                    .map(|(n, e)| format!("p{n}: {e}"))
                    .collect::<Vec<_>>()
                    .join(", ");
                tracing::warn!(
                    issue_id = %row.id,
                    pages_failed = o.failed.len(),
                    preview = %preview,
                    "thumbs job: some pages failed to encode",
                );
            }
            if matches!(
                job.kind,
                ThumbsJobKind::Cover | ThumbsJobKind::CoverAndStrip
            ) {
                stamp_done(&app, &row).await;
            }
            if matches!(
                job.kind,
                ThumbsJobKind::Strip | ThumbsJobKind::CoverAndStrip
            ) {
                if !o.failed.is_empty() {
                    let msg = format!("{} strip pages failed", o.failed.len());
                    stamp_error(&app, &row, msg).await;
                }
                // Self-heal: when the archive's actual page count disagrees
                // with the ComicInfo-derived `page_count` we stamped at scan
                // time, reconcile to the archive truth. The strip generator
                // only encodes pages that exist on disk, so leaving a stale
                // count would keep the readiness denominator chasing pages
                // that physically aren't there. Older libraries scanned
                // before scanner-side reconciliation landed pick up the fix
                // the next time their strips are (re)generated.
                reconcile_page_count(&app, &row, o.total_pages).await;
            }
            app.events.emit(ScanEvent::ThumbsCompleted {
                library_id: row.library_id,
                issue_id: row.id.clone(),
                kind: job.kind.as_str().to_owned(),
                pages: o.total_pages as u64,
            });
            app.unmark_thumb_job_queued(&dedupe_key).await;
            Ok(())
        }
        Ok(Err(e)) => {
            let msg = e.to_string();
            tracing::warn!(issue_id = %row.id, error = %e, "thumbs job: cover generation failed");
            stamp_error(&app, &row, msg.clone()).await;
            app.events.emit(ScanEvent::ThumbsFailed {
                library_id: row.library_id,
                issue_id: row.id.clone(),
                kind: job.kind.as_str().to_owned(),
                error: msg,
            });
            app.unmark_thumb_job_queued(&dedupe_key).await;
            Ok(())
        }
        Err(e) => {
            let msg = format!("worker panic: {e}");
            tracing::error!(issue_id = %row.id, error = %e, "thumbs job: blocking task panicked");
            stamp_error(&app, &row, msg.clone()).await;
            app.events.emit(ScanEvent::ThumbsFailed {
                library_id: row.library_id,
                issue_id: row.id.clone(),
                kind: job.kind.as_str().to_owned(),
                error: msg,
            });
            app.unmark_thumb_job_queued(&dedupe_key).await;
            Err(Error::Failed(std::sync::Arc::new(Box::new(e))))
        }
    }
}

pub async fn enqueue_thumb_job(app: &AppState, job: ThumbsJob) -> bool {
    let key = job.dedupe_key();
    if !app.try_mark_thumb_job_queued(key.clone()).await {
        tracing::debug!(issue_id = %job.issue_id, kind = ?job.kind, "thumbs enqueue: duplicate suppressed");
        return false;
    }

    let mut storage = app.jobs.post_scan_thumbs_storage.clone();
    if let Err(e) = storage.push(job.clone()).await {
        app.unmark_thumb_job_queued(&key).await;
        tracing::warn!(
            issue_id = %job.issue_id,
            kind = ?job.kind,
            error = %e,
            "thumbs enqueue: push failed",
        );
        return false;
    }
    true
}

async fn stamp_done(app: &AppState, row: &issue::Model) {
    let now = chrono::Utc::now().fixed_offset();
    let mut am: issue::ActiveModel = row.clone().into();
    am.thumbnails_generated_at = Set(Some(now));
    am.thumbnail_version = Set(THUMBNAIL_VERSION);
    am.thumbnails_error = Set(None);
    am.updated_at = Set(now);
    if let Err(e) = am.update(&app.db).await {
        tracing::warn!(issue_id = %row.id, error = %e, "thumbs job: stamp_done update failed");
    }
}

/// Update `issue.page_count` to the archive's actual page count when the
/// strip generator's view of reality differs from the row's stamped value.
/// No-op when the counts already agree or when the archive yielded zero
/// pages (which only happens on malformed/encrypted archives the strip
/// handler would never reach a successful outcome for anyway).
async fn reconcile_page_count(app: &AppState, row: &issue::Model, archive_pages: usize) {
    if archive_pages == 0 {
        return;
    }
    let next = archive_pages as i32;
    if row.page_count == Some(next) {
        return;
    }
    let now = chrono::Utc::now().fixed_offset();
    let mut am: issue::ActiveModel = row.clone().into();
    am.page_count = Set(Some(next));
    am.updated_at = Set(now);
    match am.update(&app.db).await {
        Ok(_) => {
            tracing::info!(
                issue_id = %row.id,
                previous = ?row.page_count,
                actual = next,
                "thumbs job: reconciled page_count to archive truth",
            );
        }
        Err(e) => {
            tracing::warn!(
                issue_id = %row.id,
                error = %e,
                "thumbs job: page_count reconcile update failed",
            );
        }
    }
}

async fn stamp_error(app: &AppState, row: &issue::Model, msg: String) {
    let now = chrono::Utc::now().fixed_offset();
    let mut am: issue::ActiveModel = row.clone().into();
    am.thumbnails_error = Set(Some(msg));
    am.updated_at = Set(now);
    if let Err(e) = am.update(&app.db).await {
        tracing::warn!(issue_id = %row.id, error = %e, "thumbs job: stamp_error update failed");
    }
}

/// Bulk-enqueue a cover job for every issue in `library_id` whose cover
/// thumbnail is missing (`thumbnails_generated_at IS NULL`) or stale
/// (`thumbnail_version < THUMBNAIL_VERSION`). Returns the number of jobs
/// pushed after process-local dedupe. Best-effort — if the apalis push fails
/// for any issue, the error is logged and the loop continues.
///
/// Honors the per-library `thumbnails_enabled` toggle: when disabled, the
/// function returns `0` without enqueueing anything. Existing on-disk
/// thumbnails keep serving; the admin can flip the toggle back on or run
/// "Generate missing" later.
pub async fn enqueue_pending_for_library(app: &AppState, library_id: Uuid) -> usize {
    match library::Entity::find_by_id(library_id).one(&app.db).await {
        Ok(Some(lib)) if !lib.thumbnails_enabled => {
            tracing::debug!(
                library_id = %library_id,
                "thumbs enqueue: library has thumbnails disabled, skipping",
            );
            return 0;
        }
        Ok(Some(_)) => {}
        Ok(None) => {
            tracing::debug!(library_id = %library_id, "thumbs enqueue: library gone");
            return 0;
        }
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "thumbs enqueue: library lookup failed");
            return 0;
        }
    }

    let pending: Vec<String> = match issue::Entity::find()
        .filter(issue::Column::LibraryId.eq(library_id))
        .filter(issue::Column::State.eq("active"))
        .filter(
            Condition::any()
                .add(issue::Column::ThumbnailsGeneratedAt.is_null())
                .add(issue::Column::ThumbnailVersion.lt(THUMBNAIL_VERSION)),
        )
        .select_only()
        .column(issue::Column::Id)
        .into_tuple::<String>()
        .all(&app.db)
        .await
    {
        Ok(v) => v,
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "thumbs enqueue: query failed");
            return 0;
        }
    };

    let mut count = 0usize;
    for issue_id in pending {
        if enqueue_thumb_job(app, ThumbsJob::cover(issue_id)).await {
            count += 1;
        }
    }
    if count > 0 {
        tracing::info!(library_id = %library_id, count, "thumbs enqueue: pushed jobs");
    }
    count
}

/// Enqueue pending cover jobs for active issues in one series only.
pub async fn enqueue_pending_for_series(
    app: &AppState,
    library_id: Uuid,
    series_id: Uuid,
) -> usize {
    let ids: Vec<String> = match issue::Entity::find()
        .filter(issue::Column::LibraryId.eq(library_id))
        .filter(issue::Column::SeriesId.eq(series_id))
        .filter(issue::Column::State.eq("active"))
        .filter(
            Condition::any()
                .add(issue::Column::ThumbnailsGeneratedAt.is_null())
                .add(issue::Column::ThumbnailVersion.lt(THUMBNAIL_VERSION)),
        )
        .select_only()
        .column(issue::Column::Id)
        .into_tuple::<String>()
        .all(&app.db)
        .await
    {
        Ok(v) => v,
        Err(e) => {
            tracing::error!(library_id = %library_id, series_id = %series_id, error = %e, "thumbs enqueue: series query failed");
            return 0;
        }
    };
    enqueue_pending_for_issue_ids(app, library_id, ids).await
}

/// Post-scan eager thumbnail fanout. Scans only enqueue missing/stale cover
/// work; page-map strips remain lazy or explicit admin work so a routine scan
/// does not flood the queue with every page in the library.
pub async fn enqueue_post_scan_for_library(app: &AppState, library_id: Uuid) -> usize {
    let (rows, include_strips) = match active_issue_rows_for_thumbs(app, library_id, None).await {
        Some(pair) => pair,
        None => return 0,
    };
    enqueue_post_scan_rows(app, rows, include_strips).await
}

pub async fn enqueue_post_scan_for_series(
    app: &AppState,
    library_id: Uuid,
    series_id: Uuid,
) -> usize {
    let (rows, include_strips) =
        match active_issue_rows_for_thumbs(app, library_id, Some(series_id)).await {
            Some(pair) => pair,
            None => return 0,
        };
    enqueue_post_scan_rows(app, rows, include_strips).await
}

/// Returns the issue rows that need post-scan thumbnail work plus a flag
/// for whether the library has opted into auto page-strip generation
/// (`library.generate_page_thumbs_on_scan`). `Some((vec![], _))` means
/// "no work" — distinct from `None` which means "lookup failed, retry
/// later". The flag flows through so the row-level loop can decide
/// per-issue whether to enqueue Strip alongside Cover.
async fn active_issue_rows_for_thumbs(
    app: &AppState,
    library_id: Uuid,
    series_id: Option<Uuid>,
) -> Option<(Vec<issue::Model>, bool)> {
    let include_strips = match library::Entity::find_by_id(library_id).one(&app.db).await {
        Ok(Some(lib)) if !lib.thumbnails_enabled => {
            tracing::debug!(
                library_id = %library_id,
                "post-scan thumbs enqueue: library has thumbnails disabled, skipping",
            );
            return Some((Vec::new(), false));
        }
        Ok(Some(lib)) => lib.generate_page_thumbs_on_scan,
        Ok(None) => return Some((Vec::new(), false)),
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "post-scan thumbs enqueue: library lookup failed");
            return None;
        }
    };

    let mut query = issue::Entity::find()
        .filter(issue::Column::LibraryId.eq(library_id))
        .filter(issue::Column::State.eq("active"))
        .filter(
            Condition::any()
                .add(issue::Column::ThumbnailsGeneratedAt.is_null())
                .add(issue::Column::ThumbnailVersion.lt(THUMBNAIL_VERSION))
                .add(issue::Column::ThumbnailsError.is_not_null()),
        );
    if let Some(series_id) = series_id {
        query = query.filter(issue::Column::SeriesId.eq(series_id));
    }
    match query.all(&app.db).await {
        Ok(rows) => Some((rows, include_strips)),
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "post-scan thumbs enqueue: issue query failed");
            None
        }
    }
}

async fn enqueue_post_scan_rows(
    app: &AppState,
    rows: Vec<issue::Model>,
    include_strips: bool,
) -> usize {
    let mut count = 0usize;
    for row in rows {
        let cover_pending = row.thumbnails_generated_at.is_none()
            || row.thumbnail_version < THUMBNAIL_VERSION
            || row.thumbnails_error.is_some();
        if !cover_pending {
            continue;
        }
        // When the library has `generate_page_thumbs_on_scan = true`, fan
        // out to a CoverAndStrip job so the worker generates both in a
        // single archive open. When false, keep the historical
        // cover-only behavior; admins still have the manual "Generate
        // missing pages" button to fill page thumbs in later.
        let job = if include_strips {
            ThumbsJob::cover_and_strip(row.id)
        } else {
            ThumbsJob::cover(row.id)
        };
        if enqueue_thumb_job(app, job).await {
            count += 1;
        }
    }
    count
}

/// Enqueue pending cover jobs for a known set of issue ids. The DB query
/// re-checks active state and thumbnail freshness so callers can pass ids
/// gathered before ingestion updated content hashes or states.
pub async fn enqueue_pending_for_issue_ids<I>(
    app: &AppState,
    library_id: Uuid,
    issue_ids: I,
) -> usize
where
    I: IntoIterator<Item = String>,
{
    match library::Entity::find_by_id(library_id).one(&app.db).await {
        Ok(Some(lib)) if !lib.thumbnails_enabled => {
            tracing::debug!(
                library_id = %library_id,
                "thumbs enqueue: library has thumbnails disabled, skipping scoped enqueue",
            );
            return 0;
        }
        Ok(Some(_)) => {}
        Ok(None) => {
            tracing::debug!(library_id = %library_id, "thumbs enqueue: library gone");
            return 0;
        }
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "thumbs enqueue: library lookup failed");
            return 0;
        }
    }

    let ids = issue_ids.into_iter().collect::<Vec<_>>();
    if ids.is_empty() {
        return 0;
    }
    let pending: Vec<String> = match issue::Entity::find()
        .filter(issue::Column::LibraryId.eq(library_id))
        .filter(issue::Column::Id.is_in(ids))
        .filter(issue::Column::State.eq("active"))
        .filter(
            Condition::any()
                .add(issue::Column::ThumbnailsGeneratedAt.is_null())
                .add(issue::Column::ThumbnailVersion.lt(THUMBNAIL_VERSION)),
        )
        .select_only()
        .column(issue::Column::Id)
        .into_tuple::<String>()
        .all(&app.db)
        .await
    {
        Ok(v) => v,
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "thumbs enqueue: scoped query failed");
            return 0;
        }
    };

    let mut count = 0usize;
    for issue_id in pending {
        if enqueue_thumb_job(app, ThumbsJob::cover(issue_id)).await {
            count += 1;
        }
    }
    count
}

/// Enqueue one lazy page-map strip job for every active issue in a single
/// series. Mirror of `enqueue_strips_for_library` scoped to one series so
/// admins can rebuild a single book's reader page-map without touching the
/// rest of the library. Strip jobs are file-level idempotent — existing
/// page thumbnails are skipped and only missing pages are encoded.
pub async fn enqueue_strips_for_series(app: &AppState, library_id: Uuid, series_id: Uuid) -> usize {
    match library::Entity::find_by_id(library_id).one(&app.db).await {
        Ok(Some(lib)) if !lib.thumbnails_enabled => {
            tracing::debug!(
                library_id = %library_id,
                series_id = %series_id,
                "strip thumbs enqueue (series): library has thumbnails disabled, skipping",
            );
            return 0;
        }
        Ok(Some(_)) => {}
        Ok(None) => {
            tracing::debug!(library_id = %library_id, "strip thumbs enqueue (series): library gone");
            return 0;
        }
        Err(e) => {
            tracing::error!(library_id = %library_id, series_id = %series_id, error = %e, "strip thumbs enqueue (series): library lookup failed");
            return 0;
        }
    }

    let issue_ids: Vec<String> = match issue::Entity::find()
        .filter(issue::Column::LibraryId.eq(library_id))
        .filter(issue::Column::SeriesId.eq(series_id))
        .filter(issue::Column::State.eq("active"))
        .select_only()
        .column(issue::Column::Id)
        .into_tuple::<String>()
        .all(&app.db)
        .await
    {
        Ok(v) => v,
        Err(e) => {
            tracing::error!(library_id = %library_id, series_id = %series_id, error = %e, "strip thumbs enqueue (series): query failed");
            return 0;
        }
    };

    let mut count = 0usize;
    for issue_id in issue_ids {
        if enqueue_thumb_job(app, ThumbsJob::strip(issue_id)).await {
            count += 1;
        }
    }
    if count > 0 {
        tracing::info!(library_id = %library_id, series_id = %series_id, count, "strip thumbs enqueue (series): pushed jobs");
    }
    count
}

/// Enqueue one lazy page-map strip job for every active issue in a library.
/// Strip jobs are idempotent at the file level: existing page thumbnails are
/// skipped and only missing pages are decoded/encoded.
pub async fn enqueue_strips_for_library(app: &AppState, library_id: Uuid) -> usize {
    match library::Entity::find_by_id(library_id).one(&app.db).await {
        Ok(Some(lib)) if !lib.thumbnails_enabled => {
            tracing::debug!(
                library_id = %library_id,
                "strip thumbs enqueue: library has thumbnails disabled, skipping",
            );
            return 0;
        }
        Ok(Some(_)) => {}
        Ok(None) => {
            tracing::debug!(library_id = %library_id, "strip thumbs enqueue: library gone");
            return 0;
        }
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "strip thumbs enqueue: library lookup failed");
            return 0;
        }
    }

    let issue_ids: Vec<String> = match issue::Entity::find()
        .filter(issue::Column::LibraryId.eq(library_id))
        .filter(issue::Column::State.eq("active"))
        .select_only()
        .column(issue::Column::Id)
        .into_tuple::<String>()
        .all(&app.db)
        .await
    {
        Ok(v) => v,
        Err(e) => {
            tracing::error!(library_id = %library_id, error = %e, "strip thumbs enqueue: query failed");
            return 0;
        }
    };

    let mut count = 0usize;
    for issue_id in issue_ids {
        if enqueue_thumb_job(app, ThumbsJob::strip(issue_id)).await {
            count += 1;
        }
    }
    if count > 0 {
        tracing::info!(library_id = %library_id, count, "strip thumbs enqueue: pushed jobs");
    }
    count
}

/// Catchup sweep: enqueue thumb jobs for every library that has
/// thumbnails enabled. Used at server startup and from a daily cron so
/// previously-failed generation attempts and older-version covers eventually
/// complete without admin action. Libraries with `thumbnails_enabled = false`
/// are skipped at the query site.
pub async fn enqueue_pending_all_libraries(app: &AppState) -> usize {
    let libs: Vec<Uuid> = match library::Entity::find()
        .filter(library::Column::ThumbnailsEnabled.eq(true))
        .select_only()
        .column(library::Column::Id)
        .into_tuple::<Uuid>()
        .all(&app.db)
        .await
    {
        Ok(v) => v,
        Err(e) => {
            tracing::error!(error = %e, "thumbs catchup: list libraries failed");
            return 0;
        }
    };
    let mut total = 0usize;
    for lib_id in libs {
        total += enqueue_pending_for_library(app, lib_id).await;
    }
    if total > 0 {
        tracing::info!(total, "thumbs catchup sweep: pushed jobs");
    }
    total
}

pub async fn handle_search(job: SearchJob, _state: Data<AppState>) -> Result<(), Error> {
    tracing::debug!(
        library_id = %job.library_id,
        "post_scan_search (no-op — search_docs is upserted inline today)",
    );
    Ok(())
}

pub async fn handle_dictionary(job: DictionaryJob, _state: Data<AppState>) -> Result<(), Error> {
    tracing::debug!(
        library_id = %job.library_id,
        "post_scan_dictionary (TODO: 'did you mean' trigram refresh)",
    );
    Ok(())
}
