-- M7 relationship / similarity fixture for `just perf-explain`
-- (scripts/perf/perf-explain.sh, phase 2; WP-8.3).
--
-- The stress fixture has credits, characters, genres and tags but nothing
-- the M7/M7b surfaces feed on: no story arcs, universes, series groups,
-- AlternateSeries or curated links. This layers a deterministic,
-- library-shaped set of them onto the scanned catalogue so the
-- relationship-suggestion job, similar series, same universe, arc tie-ins
-- and the relationships GET have realistic row counts to plan against:
--
--   * 100 story arcs, named like their main series (the arc tie-in
--     detector's strongest signal). Arc 1 is a mega-event: its main series
--     plus one issue from every 6th series (~420 series). Arcs 2–100 have
--     a main series (6 issues) and 4–17 tie-in series (2 issues each).
--   * 8 universes holding 60 % of the series (~190 each), and a
--     `series_group` on every 5th series (groups of ~10; every 50th
--     carries two groups).
--   * ComicInfo AlternateSeries on issue 1 of every 25th series, naming
--     the next series (→ `crossover_with` suggestions).
--   * One deliberately "large" series for similar-series (the analogue of
--     the dev library's Amazing Spider-Man 1989, 701 credits): every
--     fixture writer + penciller credit (1,000 rows) and 300 shared
--     characters, and a tie-in issue in arcs 2–40.
--   * Curated (manual) links: 50 six-series `sequel_of` chains and one hub
--     series with 200 `see_also` links, stored as inverse pairs like the
--     write path stores them.
--
-- Idempotent. This runs only against the throwaway perf database, so it
-- resets the relationship tables wholesale (suggestions and edges are
-- regenerated by the job phase that follows).

BEGIN;

DELETE FROM series_relationship;
DELETE FROM series_relationship_suggestion;
DELETE FROM series_arcs WHERE arc_id IN (SELECT id FROM story_arc WHERE slug LIKE 'perf-arc-%');
DELETE FROM issue_arcs WHERE arc_id IN (SELECT id FROM story_arc WHERE slug LIKE 'perf-arc-%');
DELETE FROM story_arc WHERE slug LIKE 'perf-arc-%';
DELETE FROM series_universes
 WHERE universe_id IN (SELECT id FROM universe WHERE slug LIKE 'perf-universe-%');
DELETE FROM universe WHERE slug LIKE 'perf-universe-%';
UPDATE series SET series_group = NULL WHERE series_group LIKE 'Perf Group %';
UPDATE issues SET alternate_series = NULL WHERE alternate_series IS NOT NULL;
DELETE FROM series_credits WHERE person_id IS NULL AND series_id IN (
    SELECT s.id FROM series s WHERE s.series_group = 'perf-large');
DELETE FROM series_characters WHERE character_id IS NULL AND series_id IN (
    SELECT s.id FROM series s WHERE s.series_group = 'perf-large');
UPDATE series SET series_group = NULL WHERE series_group = 'perf-large';

CREATE TEMP TABLE ps ON COMMIT DROP AS
SELECT s.id, s.name, s.normalized_name,
       row_number() OVER (ORDER BY s.normalized_name, s.id)::int AS ord
FROM series s WHERE s.removed_at IS NULL;
CREATE UNIQUE INDEX ON ps (ord);
SELECT count(*) AS n FROM ps \gset

CREATE TEMP TABLE pi ON COMMIT DROP AS
SELECT i.id, i.series_id, ps.ord,
       row_number() OVER (PARTITION BY i.series_id ORDER BY i.sort_number, i.id)::int AS n
FROM issues i JOIN ps ON ps.id = i.series_id
WHERE i.state = 'active' AND i.removed_at IS NULL;
CREATE INDEX ON pi (ord, n);

-- ── story arcs ──────────────────────────────────────────────────────────
-- Arc a's main series: ord 1 for the mega-event, a * 20 otherwise.
CREATE TEMP TABLE arcs ON COMMIT DROP AS
SELECT a, CASE WHEN a = 1 THEN 1 ELSE a * 20 END AS main_ord, gen_random_uuid() AS id
FROM generate_series(1, 100) a;

INSERT INTO story_arc (id, slug, name, normalized_name, aliases, created_at, updated_at)
SELECT arcs.id, format('perf-arc-%s', arcs.a), ps.name, ps.normalized_name, '[]'::jsonb, now(), now()
FROM arcs JOIN ps ON ps.ord = arcs.main_ord;

CREATE TEMP TABLE arc_members ON COMMIT DROP AS
-- main series: issues 1–8 (mega) / 1–6
SELECT arcs.id AS arc_id, arcs.main_ord AS ord, n
FROM arcs, generate_series(1, 8) n
WHERE n <= CASE WHEN arcs.a = 1 THEN 8 ELSE 6 END
UNION
-- mega-event tie-ins: issue 10 of every 6th series
SELECT arcs.id, ps.ord, 10
FROM arcs JOIN ps ON ps.ord % 6 = 0 AND ps.ord <> arcs.main_ord
WHERE arcs.a = 1
UNION
-- arcs 2–100: 4–17 tie-in series, issues 11–12
SELECT arcs.id, ((arcs.main_ord + k * 37) % :n) + 1, n
FROM arcs, generate_series(1, 17) k, generate_series(11, 12) n
WHERE arcs.a > 1 AND k <= 4 + (arcs.a % 14)
  AND ((arcs.main_ord + k * 37) % :n) + 1 <> arcs.main_ord
UNION
-- the large series ties into arcs 2–40 (issue 13–20, cycling)
SELECT arcs.id, 7, 13 + (arcs.a % 8)
FROM arcs WHERE arcs.a BETWEEN 2 AND 40 AND arcs.main_ord <> 7;

INSERT INTO issue_arcs (issue_id, arc_id, position_in_arc)
SELECT pi.id, m.arc_id,
       (row_number() OVER (PARTITION BY m.arc_id ORDER BY m.ord, m.n))::int
FROM arc_members m JOIN pi ON pi.ord = m.ord AND pi.n = m.n
ON CONFLICT DO NOTHING;

INSERT INTO series_arcs (series_id, arc_id)
SELECT DISTINCT ps.id, m.arc_id
FROM arc_members m JOIN ps ON ps.ord = m.ord
ON CONFLICT DO NOTHING;

-- ── universes + series groups ───────────────────────────────────────────
CREATE TEMP TABLE unis ON COMMIT DROP AS
SELECT u, gen_random_uuid() AS id FROM generate_series(1, 8) u;
INSERT INTO universe (id, slug, name, normalized_name, aliases, created_at, updated_at)
SELECT id, format('perf-universe-%s', u), format('Perf Universe %s', u),
       format('perf universe %s', u), '[]'::jsonb, now(), now()
FROM unis;
INSERT INTO series_universes (series_id, universe_id)
SELECT ps.id, unis.id FROM ps JOIN unis ON unis.u = ps.ord % 8 + 1
WHERE ps.ord % 10 < 6;

UPDATE series s SET series_group = CASE
        WHEN ps.ord % 50 = 0 THEN format('Perf Group %s; Perf Group %s', ps.ord / 50, ps.ord / 50 + 1)
        ELSE format('Perf Group %s', ps.ord / 50) END
FROM ps WHERE ps.id = s.id AND ps.ord % 5 = 0;

-- ── AlternateSeries (→ crossover_with) ─────────────────────────────────
UPDATE issues i SET alternate_series = nxt.name
FROM pi JOIN ps nxt ON nxt.ord = pi.ord % :n + 1
WHERE i.id = pi.id AND pi.ord % 25 = 0 AND pi.n = 1;

-- ── the "large" series (ord 7) for similar-series ───────────────────────
UPDATE series s SET series_group = 'perf-large' FROM ps WHERE ps.id = s.id AND ps.ord = 7;
INSERT INTO series_credits (series_id, role, person)
SELECT ps.id, 'writer', format('Writer %s', lpad(w::text, 3, '0'))
FROM ps, generate_series(0, 399) w WHERE ps.ord = 7
UNION ALL
SELECT ps.id, 'penciller', format('Artist %s', lpad(p::text, 3, '0'))
FROM ps, generate_series(0, 599) p WHERE ps.ord = 7
ON CONFLICT DO NOTHING;
INSERT INTO series_characters (series_id, "character")
SELECT ps.id, format('Character %s', lpad((c * 5)::text, 4, '0'))
FROM ps, generate_series(0, 299) c WHERE ps.ord = 7
ON CONFLICT DO NOTHING;

-- ── curated links (inverse pairs) ───────────────────────────────────────
-- 50 chains of six: series 2001 + c*8 + j, each `sequel_of` the previous.
INSERT INTO series_relationship (id, from_series_id, to_series_id, kind, source)
SELECT gen_random_uuid(), x.f, x.t, x.k, 'manual'
FROM (
    SELECT b.id AS f, a.id AS t, 'sequel_of' AS k
    FROM generate_series(0, 49) c CROSS JOIN generate_series(1, 5) j
    JOIN ps a ON a.ord = 2001 + c * 8 + j - 1
    JOIN ps b ON b.ord = 2001 + c * 8 + j
    UNION ALL
    SELECT a.id, b.id, 'has_sequel'
    FROM generate_series(0, 49) c CROSS JOIN generate_series(1, 5) j
    JOIN ps a ON a.ord = 2001 + c * 8 + j - 1
    JOIN ps b ON b.ord = 2001 + c * 8 + j
    -- hub (ord 2450): 200 `see_also` links (self-inverse: both rows `see_also`)
    UNION ALL
    SELECT h.id, o.id, 'see_also'
    FROM ps h CROSS JOIN generate_series(1, 200) k
    JOIN ps o ON o.ord = (h.ord + k * 11) % :n + 1
    WHERE h.ord = 2450
    UNION ALL
    SELECT o.id, h.id, 'see_also'
    FROM ps h CROSS JOIN generate_series(1, 200) k
    JOIN ps o ON o.ord = (h.ord + k * 11) % :n + 1
    WHERE h.ord = 2450
) x
WHERE x.f <> x.t
ON CONFLICT DO NOTHING;

COMMIT;
